//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSIP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DashboardEntities : DbContext
    {
        public DashboardEntities()
            : base("name=DashboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SpNCRChart_Result> SpNCRChart()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpNCRChart_Result>("SpNCRChart");
        }
    
        public virtual ObjectResult<SpServicesChart_Result> SpServicesChart()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpServicesChart_Result>("SpServicesChart");
        }
    
        public virtual ObjectResult<Nullable<int>> SpGetNoOfDispatched()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SpGetNoOfDispatched");
        }
    }
}
